name: Table Query and Viz Benchmarking / Experience Report
description: Report your Synapse table and query viz experiment and share any discovered issues, ideas, or other insights.
title: "Table Query and Viz Experience Report"
labels: []
projects: []
assignees:
  - anngvu
body:
  - type: markdown
    attributes:
      value: |
        ## Instructions for trying out table query and viz with Syndi
        - [ ] Choose a table that you know well and that another Sage employee can access to allow easier reproduction and understanding.
        - [ ] Add documentation to the table's root Wiki page.
           Try to at least describe the columns and provide at least 1-2 example queries. 
           These are inserted as context and allows you to do "prompt engineering"; experiment with this contextual content to improve the results. 
        - [ ] Create benchmark questions. The number of questions depend on your table, but try for at least 3 questions with a variety ranging from "easy" to "hard". 
        ## How your report will be used
        Shared results will be used to understand:
        - What type of Synapse table data are of interest/fair game (aside from the obvious portal-related tables)
        - How types of table data work well or not with the current defaults
        - How users try to optimize documentation for AI reusability
        - Range of natural queries and conversation flow for table-related tasks, and what common issues may look like
  - type: input
    id: table-id
    attributes:
      label: Synapse Table 
      description: Please enter the Synapse ID of your table.
      placeholder: syn123456
    validations:
      required: true
  - type: textarea
    id: questions
    attributes:
      label: What questions did you use?
      description: Attach documentation for questions you used or copy and paste them below. You can provide additional characterization of the questions such as "easy", "medium", or "hard" and your impression of the resultant answer and/or visualization.
      value: "Here are my questions and assessment: "
    validations:
      required: true
  - type: textarea
    id: experience
    attributes:
      label: Other Evaluation Insights
      description: Share any other insights you have
      value: "I found that... "
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of accent did you run?
      options:
        - v0.5-rc3 (Default)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browser did you use?
      multiple: false
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Saved chat
      description: (Optional) If you saved the chat to file and it is appropriate for sharing publicly and you are comfortable sharing publicly, attach it here. Otherwise, upload it to Synapse for more fine-grained access and share it with `avu`, and make a note of the Synapse ID here.

