#!/usr/bin/env bash

set -euo pipefail

JAVA_VERSION="java17"
GRAALVM_VERSION="${GRAALVM_VERSION:-22.3.1}"
# e.g. https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.1/graalvm-ce-java17-linux-amd64-22.3.1.tar.gz

case "$DTLV_PLATFORM" in
	macos)
		GRAALVM_PLATFORM="darwin"
		;;
	linux)
		GRAALVM_PLATFORM="linux"
		;;
esac

case "${DTLV_ARCH:-}" in
	aarch64)
		GRAALVM_ARCH="aarch64"
		;;
	*)
		GRAALVM_ARCH="amd64"
		;;
esac

GRAALVM_FILENAME="graalvm-ce-$JAVA_VERSION-$GRAALVM_PLATFORM-$GRAALVM_ARCH-$GRAALVM_VERSION.tar.gz"

if ! [ -d "graalvm-ce-$JAVA_VERSION-$GRAALVM_VERSION" ]; then
	echo "Downloading GraalVM $GRAALVM_PLATFORM-$GRAALVM_ARCH-$GRAALVM_VERSION on '$PWD'..."
	wget -nv "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-$GRAALVM_VERSION/$GRAALVM_FILENAME"
	tar xzf "$GRAALVM_FILENAME"
  graalvm-ce-$JAVA_VERSION-$GRAALVM_VERSION/Contents/Home/bin/gu install native-image
fi
